icons_format = "{icon}"

[theme]
theme = "plain"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "awesome4"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "pomodoro"
# length = 25
# break_length = 5
message = "Take a break!"
break_message = "Back to work!"
notify_cmd = "notify-send '{msg}'"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4) "

[[block]]
block = "memory"
format = " $icon $mem_used_percents $icon_swap $swap_used_percents "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20

[[block]]
block = "net"
device = "enx"
format = " $icon {$ip} "

[[block]]
block = "net"
device = "wl"
format = " $icon {$ssid $ip} "

[[block]]
block = "bluetooth"
mac = "18:26:54:69:AA:25"
format = " $icon Buds2{ $percentage|} "
disconnected_format = " $icon Buds2 "
[block.battery_state]
"0..20" = "critical"
"21..40" = "warning"
"41..100" = "good"

[[block]]
block = "sound"
format = " $output_name $icon {$volume.eng(w:2) |}"
[block.mappings]
"bluez_output.*" = "B"
"alsa_output.pci.*" = "S"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
device = "amdgpu_bl1"

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m) |} "
full_format = " $icon $percentage "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
